INSERT INTO USER (ID , USERNAME , PASSWORD , MANAGECOM) VALUES ('1', 'admin', 'admin', 'A');
INSERT INTO USER (ID , USERNAME , PASSWORD , MANAGECOM) VALUES ('2', 'zhangsan', '12345', 'A');
INSERT INTO USER (ID , USERNAME , PASSWORD , MANAGECOM) VALUES ('3', 'lisi', '11111', 'B');
INSERT INTO USER (ID , USERNAME , PASSWORD , MANAGECOM) VALUES ('4', 'wangwu', '22222', 'B');
INSERT INTO USER (ID , USERNAME , PASSWORD , MANAGECOM) VALUES ('5', 'zhaoliu', '33333', 'C');
INSERT INTO USER (ID , USERNAME , PASSWORD , MANAGECOM) VALUES ('6', 'Tom', '33333', 'D');
INSERT INTO USER (ID , USERNAME , PASSWORD , MANAGECOM) VALUES ('7', 'Jim', '33333', 'D');
INSERT INTO USER (ID , USERNAME , PASSWORD , MANAGECOM) VALUES ('8', 'Kevin', '33333', 'D');