INSERT INTO USER (ID , USERNAME , PASSWORD) VALUES ('1', 'admin', 'admin');
INSERT INTO USER (ID , USERNAME , PASSWORD) VALUES ('2', 'zhangsan', '12345');
INSERT INTO USER (ID , USERNAME , PASSWORD) VALUES ('3', 'lisi', '11111');
INSERT INTO USER (ID , USERNAME , PASSWORD) VALUES ('4', 'wangwu', '22222');
INSERT INTO USER (ID , USERNAME , PASSWORD) VALUES ('5', 'zhaoliu', '33333');